// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBBwFU6UpeYMhBgF_qT_8TyovH08OoNlM',
    appId: '1:658530917076:web:c0f6ac6b205207691d3941',
    messagingSenderId: '658530917076',
    projectId: 'activelife-4c27a',
    authDomain: 'activelife-4c27a.firebaseapp.com',
    storageBucket: 'activelife-4c27a.firebasestorage.app',
    measurementId: 'G-WQXHLHHJNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhV_ubQQqRWSYA_20K6pWclzaCHEBBhdQ',
    appId: '1:658530917076:android:1b2a5aab3d9280221d3941',
    messagingSenderId: '658530917076',
    projectId: 'activelife-4c27a',
    storageBucket: 'activelife-4c27a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1JXnNpS15S-SQWUL1fevUagWII8hR1xU',
    appId: '1:658530917076:ios:1e45de340d35b6bf1d3941',
    messagingSenderId: '658530917076',
    projectId: 'activelife-4c27a',
    storageBucket: 'activelife-4c27a.firebasestorage.app',
    iosBundleId: 'com.example.activelife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1JXnNpS15S-SQWUL1fevUagWII8hR1xU',
    appId: '1:658530917076:ios:1e45de340d35b6bf1d3941',
    messagingSenderId: '658530917076',
    projectId: 'activelife-4c27a',
    storageBucket: 'activelife-4c27a.firebasestorage.app',
    iosBundleId: 'com.example.activelife',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBBwFU6UpeYMhBgF_qT_8TyovH08OoNlM',
    appId: '1:658530917076:web:691cbe5b374fc6971d3941',
    messagingSenderId: '658530917076',
    projectId: 'activelife-4c27a',
    authDomain: 'activelife-4c27a.firebaseapp.com',
    storageBucket: 'activelife-4c27a.firebasestorage.app',
    measurementId: 'G-JQDCG88FH4',
  );
}
